#!/usr/bin/env ruby

require 'rancher_deployer'

action = ENV.fetch('PLUGIN_ACTION', 'deploy').to_sym

case action
when :deploy
  deployer = RancherDeployer::Deployer.new
  deployer.deploy!
when :tag_check
  tag_checker = RancherDeployer::TagChecker.new
  tag_checker.check!
end
